package bundler

import (
	"bytes"
	"fmt"
	"io"
	"path/filepath"

	"github.com/Hayao0819/seira/internal/shellparse"
	"github.com/cockroachdb/errors"
	"mvdan.cc/sh/v3/syntax"
)

// ConcatMode bundles scripts by concatenating them into a single file.
// Function definitions are collected at the top, side effects follow in
// topological (source) order, and source statements are removed.
type ConcatMode struct{}

type funcBlock struct {
	origin string // relative path of the source file
	name   string
	stmt   *syntax.Stmt
}

type effectBlock struct {
	origin string
	stmt   *syntax.Stmt
}

func (m *ConcatMode) Generate(ctx *BundleContext) error {
	printer := syntax.NewPrinter()
	if ctx.Minify {
		printer = syntax.NewPrinter(syntax.Minify(true))
	}

	var funcs []funcBlock
	var effects []effectBlock

	// Process files in topological order (deps first, entrypoint last)
	for _, path := range ctx.Order {
		node := ctx.Graph.Node(path)
		if node == nil || node.Script == nil {
			continue
		}

		rel, err := filepath.Rel(ctx.BaseDir, path)
		if err != nil {
			rel = path
		}

		classified := shellparse.ClassifyStmts(node.Script.File.Stmts)
		for _, cs := range classified {
			switch cs.Kind {
			case shellparse.StmtFunc:
				funcs = append(funcs, funcBlock{
					origin: rel,
					name:   cs.FuncName,
					stmt:   cs.Stmt,
				})
			case shellparse.StmtSource:
				// Skip — dependencies are already resolved
				continue
			case shellparse.StmtEffect:
				effects = append(effects, effectBlock{
					origin: rel,
					stmt:   cs.Stmt,
				})
			}
		}
	}

	// Write output
	w := ctx.Output

	// Shebang
	fmt.Fprintf(w, "#!%s\n", ctx.Shebang)
	fmt.Fprintln(w, "# Generated by seira (concat mode)")
	fmt.Fprintln(w)

	// Function definitions
	if len(funcs) > 0 {
		fmt.Fprintln(w, "# === Function definitions ===")
		currentOrigin := ""
		for _, f := range funcs {
			if f.origin != currentOrigin {
				currentOrigin = f.origin
				fmt.Fprintf(w, "\n# from %s\n", currentOrigin)
			}
			if err := printStmt(printer, w, f.stmt); err != nil {
				return errors.Wrapf(err, "printing function %s", f.name)
			}
		}
		fmt.Fprintln(w)
	}

	// Side effects
	if len(effects) > 0 {
		fmt.Fprintln(w, "# === Side effects ===")
		currentOrigin := ""
		for _, e := range effects {
			if e.origin != currentOrigin {
				currentOrigin = e.origin
				fmt.Fprintf(w, "\n# from %s\n", currentOrigin)
			}
			if err := printStmt(printer, w, e.stmt); err != nil {
				return errors.Wrap(err, "printing side effect")
			}
		}
		fmt.Fprintln(w)
	}

	// Entry point
	fmt.Fprintln(w, "# === Entry point ===")
	fmt.Fprintln(w, `main "$@"`)

	return nil
}

func printStmt(printer *syntax.Printer, w io.Writer, stmt *syntax.Stmt) error {
	var buf bytes.Buffer
	if err := printer.Print(&buf, stmt); err != nil {
		return err
	}
	_, err := fmt.Fprintln(w, buf.String())
	return err
}
