package bundler

import (
	"bytes"
	"fmt"
	"io"

	"github.com/Hayao0819/seira/assets"
	"github.com/Hayao0819/seira/internal/shellparse"
	"github.com/cockroachdb/errors"
	"mvdan.cc/sh/v3/syntax"
)


// ConcatMode bundles scripts by concatenating them into a single file.
// Function definitions are collected at the top, side effects follow in
// topological (source) order, and source statements are removed.
type ConcatMode struct{}

type funcBlock struct {
	origin string // relative path of the source file
	name   string
	stmt   *syntax.Stmt
}

type effectBlock struct {
	origin string
	stmt   *syntax.Stmt
}

func (m *ConcatMode) Generate(ctx *BundleContext) error {
	printer := syntax.NewPrinter()
	if ctx.Minify {
		printer = syntax.NewPrinter(syntax.Minify(true))
	}

	var funcs []funcBlock
	var effects []effectBlock
	usingNamespaces := map[string]bool{}

	// Process files in topological order (deps first, entrypoint last)
	for _, path := range ctx.Order {
		node := ctx.Graph.Node(path)
		if node == nil || node.Script == nil {
			continue
		}

		rel := relativePath(ctx.BaseDir, path)

		classified := shellparse.ClassifyStmts(node.Script.File.Stmts)
		for _, cs := range classified {
			// Collect @seira:using directives from all statements
			for _, d := range cs.Directives.GetAll("using") {
				if d.Args != "" {
					usingNamespaces[d.Args] = true
				}
			}

			switch cs.Kind {
			case shellparse.StmtFunc:
				funcs = append(funcs, funcBlock{
					origin: rel,
					name:   cs.FuncName,
					stmt:   cs.Stmt,
				})
			case shellparse.StmtSource:
				if cs.Directives.Has("ignore") {
					// @seira:ignore — keep source line for runtime resolution
					effects = append(effects, effectBlock{origin: rel, stmt: cs.Stmt})
					continue
				}
				// Skip — dependencies are already resolved
				continue
			case shellparse.StmtEffect:
				effects = append(effects, effectBlock{
					origin: rel,
					stmt:   cs.Stmt,
				})
			}
		}
	}

	// Tree shake: remove unreachable functions
	if ctx.TreeShake {
		funcs = TreeShake(funcs, effects, []string{"main"})
	}

	// Build namespace aliases from @seira:using directives
	aliases := resolveNamespaceAliases(funcs, usingNamespaces)

	// Write output
	w := ctx.Output

	// Shebang
	fmt.Fprintf(w, "#!%s\n", ctx.Shebang)
	fmt.Fprintln(w, "# Generated by seira (concat mode)")
	fmt.Fprintln(w)

	// seira_path runtime function (for deps access)
	if ctx.HasDeps {
		fmt.Fprintln(w, "# === seira_path runtime ===")
		fmt.Fprintln(w, assets.SeiraPathFunc)
		fmt.Fprintln(w)
	}

	// Function definitions
	if len(funcs) > 0 {
		fmt.Fprintln(w, "# === Function definitions ===")
		currentOrigin := ""
		for _, f := range funcs {
			if f.origin != currentOrigin {
				currentOrigin = f.origin
				fmt.Fprintf(w, "\n# from %s\n", currentOrigin)
			}
			if err := printStmt(printer, w, f.stmt); err != nil {
				return errors.Wrapf(err, "printing function %s", f.name)
			}
		}
		fmt.Fprintln(w)
	}

	// Namespace aliases (@seira:using)
	if len(aliases) > 0 {
		fmt.Fprintln(w, "# === Namespace aliases ===")
		for _, a := range aliases {
			fmt.Fprintf(w, "%s() { %s \"$@\"; }\n", a.shortName, a.fullName)
		}
		fmt.Fprintln(w)
	}

	// Side effects
	if len(effects) > 0 {
		fmt.Fprintln(w, "# === Side effects ===")
		currentOrigin := ""
		for _, e := range effects {
			if e.origin != currentOrigin {
				currentOrigin = e.origin
				fmt.Fprintf(w, "\n# from %s\n", currentOrigin)
			}
			if err := printStmt(printer, w, e.stmt); err != nil {
				return errors.Wrap(err, "printing side effect")
			}
		}
		fmt.Fprintln(w)
	}

	// Entry point
	fmt.Fprintln(w, "# === Entry point ===")
	fmt.Fprintln(w, `main "$@"`)

	return nil
}

func printStmt(printer *syntax.Printer, w io.Writer, stmt *syntax.Stmt) error {
	var buf bytes.Buffer
	if err := printer.Print(&buf, stmt); err != nil {
		return err
	}
	_, err := fmt.Fprintln(w, buf.String())
	return err
}
