package bundler

import (
	"fmt"
	"strings"

	"github.com/Hayao0819/seira/internal/shellparse"
	"github.com/cockroachdb/errors"
	"mvdan.cc/sh/v3/syntax"
)

// LibraryMode bundles scripts as a sourceable library.
// No shebang, no main "$@", just function definitions and side effects.
type LibraryMode struct{}

func (m *LibraryMode) Generate(ctx *BundleContext) error {
	printer := syntax.NewPrinter()
	if ctx.Minify {
		printer = syntax.NewPrinter(syntax.Minify(true))
	}

	// Build export set for filtering
	exportSet := make(map[string]bool)
	for _, name := range ctx.Exports {
		exportSet[name] = true
	}
	filterExports := len(exportSet) > 0

	var funcs []funcBlock
	var effects []effectBlock
	usingNamespaces := map[string]bool{}

	for _, path := range ctx.Order {
		node := ctx.Graph.Node(path)
		if node == nil || node.Script == nil {
			continue
		}

		rel := relativePath(ctx.BaseDir, path)

		classified := shellparse.ClassifyStmts(node.Script.File.Stmts)
		for _, cs := range classified {
			for _, d := range cs.Directives.GetAll("using") {
				if d.Args != "" {
					usingNamespaces[d.Args] = true
				}
			}

			switch cs.Kind {
			case shellparse.StmtFunc:
				if filterExports && !exportSet[cs.FuncName] {
					continue
				}
				funcs = append(funcs, funcBlock{
					origin: rel,
					name:   cs.FuncName,
					stmt:   cs.Stmt,
				})
			case shellparse.StmtSource:
				if cs.Directives.Has("ignore") {
					effects = append(effects, effectBlock{origin: rel, stmt: cs.Stmt})
					continue
				}
				continue
			case shellparse.StmtEffect:
				effects = append(effects, effectBlock{
					origin: rel,
					stmt:   cs.Stmt,
				})
			}
		}
	}

	aliases := resolveNamespaceAliases(funcs, usingNamespaces)

	w := ctx.Output

	// Library header
	fmt.Fprintln(w, "# Generated by seira (library mode)")
	if ctx.LibraryName != "" {
		fmt.Fprintf(w, "# seira-library: %s\n", ctx.LibraryName)
	}
	if len(funcs) > 0 {
		names := make([]string, 0, len(funcs))
		for _, f := range funcs {
			names = append(names, f.name)
		}
		fmt.Fprintf(w, "# seira-exports: %s\n", strings.Join(names, " "))
	}
	fmt.Fprintln(w)

	// Function definitions
	if len(funcs) > 0 {
		fmt.Fprintln(w, "# === Function definitions ===")
		currentOrigin := ""
		for _, f := range funcs {
			if f.origin != currentOrigin {
				currentOrigin = f.origin
				fmt.Fprintf(w, "\n# from %s\n", currentOrigin)
			}
			if err := printStmt(printer, w, f.stmt); err != nil {
				return errors.Wrapf(err, "printing function %s", f.name)
			}
		}
		fmt.Fprintln(w)
	}

	// Namespace aliases
	if len(aliases) > 0 {
		fmt.Fprintln(w, "# === Namespace aliases ===")
		for _, a := range aliases {
			fmt.Fprintf(w, "%s() { %s \"$@\"; }\n", a.shortName, a.fullName)
		}
		fmt.Fprintln(w)
	}

	// Side effects
	if len(effects) > 0 {
		fmt.Fprintln(w, "# === Side effects ===")
		currentOrigin := ""
		for _, e := range effects {
			if e.origin != currentOrigin {
				currentOrigin = e.origin
				fmt.Fprintf(w, "\n# from %s\n", currentOrigin)
			}
			if err := printStmt(printer, w, e.stmt); err != nil {
				return errors.Wrap(err, "printing side effect")
			}
		}
	}

	return nil
}
